version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "clash" ]
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "clash", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-app

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: clash
      POSTGRES_PASSWORD: clash
      POSTGRES_DB: clash
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-app

  cassandra-node-1:
    image: cassandra:4.1
    container_name: cassandra-node-1
    hostname: cassandra-node-1
    # ports:
    #   - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "cassandra-node-1"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    volumes:
      - cassandra1-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe keyspaces'" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - chat-app

  # ----- i don't have enough ram to run 2 cassandra node -----
  # cassandra-node-2:
  #   image: cassandra:4.1
  #   container_name: cassandra-node-2
  #   hostname: cassandra-node-2
  #   depends_on:
  #     cassandra-node-1:
  #       condition: service_healthy
  #   environment:
  #     CASSANDRA_CLUSTER_NAME: "MyCluster"
  #     CASSANDRA_DC: "dc1"
  #     CASSANDRA_RACK: "rack1"
  #     CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
  #     CASSANDRA_SEEDS: "cassandra-node-1"
  #     MAX_HEAP_SIZE: 512M
  #     HEAP_NEWSIZE: 128M
  #   volumes:
  #     - cassandra2-data:/var/lib/cassandra
  #   networks:
  #     - chat-app

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    depends_on:
      cassandra-node-1:
        condition: service_healthy
    # ports:
    #   - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo > /dev/tcp/127.0.0.1/2181" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - chat-app

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list" ]
      interval: 60s
      timeout: 60s
      retries: 10
    networks:
      - chat-app

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      # CORS_ORIGIN: http://frontend:3000
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      KAFKA_BROKERS: kafka:9092
      CASSANDRA_DB: cassandra-node-1
    # ports:
    #   - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      cassandra-node-1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - chat-app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chat-app

  nginx:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - frontend
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge

volumes:
  postgres_data:
  cassandra1-data:
  cassandra2-data: