services:
  redis:
    image: redis:alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "clash" ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "clash", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-app

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: clash
      POSTGRES_PASSWORD: clash
      POSTGRES_DB: clash
    ports:
      - "5432:5432"
    networks:
      - chat-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra-node-1:
    image: cassandra:4.1
    container_name: cassandra-node-1
    hostname: cassandra-node-1
    ports:
      - "9042:9042" # CQL
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "cassandra-node-1"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    volumes:
      - cassandra1-data:/var/lib/cassandra
    networks:
      - chat-app

  cassandra-node-2:
    image: cassandra:4.1
    container_name: cassandra-node-2
    hostname: cassandra-node-2
    depends_on:
      - cassandra-node-1
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "cassandra-node-1"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    volumes:
      - cassandra2-data:/var/lib/cassandra
    networks:
      - chat-app

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    networks:
      - chat-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: clash@gmail.com
      PGADMIN_DEFAULT_PASSWORD: clash
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - chat-app
    attach: false

networks:
  chat-app:


volumes:
  postgres_data:
  cassandra1-data:
  cassandra2-data: