
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    # restart: unless-stopped
    environment:
      POSTGRES_USER: clash
      POSTGRES_PASSWORD: clash
      POSTGRES_DB: clash
    ports:
      - "5432:5432"
    networks:
      - chat-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 30s
      retries: 5
    attach: false
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: redis
    # restart: unless-stopped
    command: ["redis-server", "--requirepass", "clash"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "clash", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - chat-app

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    # restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - chat-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: clash@gmail.com
      PGADMIN_DEFAULT_PASSWORD: clash
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - chat-app
    attach: false

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: admin123
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000" # S3 API
  #     - "9001:9001" # Web Console
  #   networks:
  #     - chat-app
  #   volumes:
  #     - minio_data:/data

networks:
  chat-app:


volumes:
  postgres_data:
  redis_data:
  # minio_data:
